### ISSUE TITLE
Write tests to ensure all Listener classes have proper annotations

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/perworldinventory-kt#20]
Just like in the Java PWI, test that all event handling methods have teh `@EventHandler` annotation.

Reference: https://github.com/Gnat008/PerWorldInventory/blob/master/src/test/java/me/gnat008/perworldinventory/listeners/ListenerConsistencyTest.java

**Comment by ljacqu** [comment]
I could do it if you want. I'd be interested in using [org.reflections](https://github.com/ronmamo/reflections) to get the classes this time, instead of the ClassCollector that is in the Java version.

**Comment by Gnat008** [comment]
Closed with https://github.com/Gnat008/perworldinventory-kt/commit/c893b60c4dd5f822f37cf198bc8a73f8c6e79aeb with my thanks! :D
