### ISSUE TITLE
Creating a new group on the fly despite world already existing in worlds.json.

### ISSUE THREAD

**Issue by mibby** [Gnat008/perworldinventory-kt#34]
PerWorldInventory-KT dev 50
Paper dev 1410 (Spigot 1.12.2)

Testing KT version with PWI 1.x files / conversion.

Worlds.json file created migrated from PWI 1.x worlds.yml.

```
{
  "groups": {
    "default": {
      "worlds": [
        "world",
        "world_nether",
        "world_the_end",
        "spawn",
        "darkzone",
        "void",
        "thelab"
      ]
    },
    "build": {
      "worlds": [
        "build1",
        "build2"
      ]
    }
  }
}
```
```
[16:41:05] [Server thread/WARN]: [PerWorldInventory] Creating a new group on the fly for 'world'. Please double check your `worlds.json` file configuration!
```

**Comment by Gnat008** [comment]
@mibby is this still present in the current RC builds?

**Comment by x0Z3ro0x** [comment]
No worlds share inventories so no worlds were added to the worlds.yml file. The file is currently default and looks like this:

`# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
`

**Comment by Gnat008** [comment]
@x0Z3ro0x ...I suppose I can see the value in a setup like that. The console message was an effort to get people who had (usually accidentally) misconfigured their worlds to go back and check it, as this has caused problems in the past. Would a setting to disable the nag message be acceptable?

I don't think it's a good idea to just add on-the-fly groups to the `worlds.yml` file, in case a server owner changes something and it causes unexpected behaviour.

**Comment by x0Z3ro0x** [comment]
There is major value in the setup we have. We have found a way using your plugin and several others, to make a server act and serve users as if it were a dozen servers in one. Each world acting as its own. It's own currency, game-mode, etc. So for us, it isn't laziness that has our worlds.yml file empty but rather the need for it to be like that. NO not ONE single world is shared with another. Not even the main world.

To answer your question, simply. Yes. I personally find a setting to disable that more than acceptable, I would call it a flat out fix.

As for your last part, I can't speak on that. If you feel it isn't a good idea, the most I can say is you know what you are doing, so do it. All we can do is trust you and if something breaks we report it here.

**Comment by Gnat008** [comment]
Added setting to disable the nag message. :)
I'll put up a new release with that and the other couple of fixes from today.

**Comment by mibby** [comment]
Disabling the nag message works for me. :)
