### ISSUE TITLE
KT2.0(B8) Item duplication with pre-existing data

### ISSUE THREAD

**Issue by Frosthaven** [Gnat008/perworldinventory-kt#37]
**explanation**
 * Let's assume you have two worlds: `world_a` and `world_b`.
 * Let's assume your respawn location is in `world a` at your bed.
 * Let's assume both worlds are under different groups in `worlds.yml`.

If you die in `world_b`, your items fall to the ground and you are returned to `world_a` as expected. Upon re-entering `world_b`, your inventory is restored *and* the items from your death are still on the ground - effectively duplicating your inventory on death.

**caveat**
This only occurs if pre-existing saved data is found from an earlier version (maybe only the betas?). Deleting the data folder and relaunching the server will wipe all inventories and prevent this bug from occurring. No errors are logged to the console when this happens.

Happy to record gameplay or delve into the JSON upon request.

**Comment by Frosthaven** [comment]
Important Update: More debugging with fresh data. Item duplication can be triggered in this way:

1. have a creative world and a survival world
2. set your spawn in the creative world
2. go to the survival world and give yourself a sand
3. go to the creative world and leave
4. go to the survival world and /kill yourself
5. after respawning back in the creative world, re-enter the survival world.
6. you now have items in your hand and items from your death on the ground.

**Comment by Gnat008** [comment]
Guess who forgot to re-implement the death listener.... :wave:

**Comment by Gnat008** [comment]
Beta 9 is out and contains the fix for this.
