### ISSUE TITLE
My economy balance gets reset when I travel to a world and back or switch gamemodes and switch back.

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/perworldinventory-kt#38]
Copy from https://github.com/Gnat008/PerWorldInventory/issues/319
It's prolly an issue here as well. Best bet is probably to check to see if the end amount is less than 0, and adjust accordingly. Would be so much nicer if Vault had a `setBalance(double)` method....

@Twingary said:
Hi, I recently started using PerWorldInventory specifically so I could separate the economies between my creative world and survival world. But I've ran into an issue that when I switch gamemodes and switch back, I will get this issue in the console:

```
[Sat, 5. May 2018 20:27:50 EDT INFO] twingary issued server command: /gmc
[Sat, 5. May 2018 20:27:50 EDT WARN] [PerWorldInventory] [ECON] Unable to withdraw funds from 'twingary': Cannot withdraw negative funds
[Sat, 5. May 2018 20:27:51 EDT INFO] twingary issued server command: /bal
[Sat, 5. May 2018 20:27:53 EDT INFO] twingary issued server command: /gms
[Sat, 5. May 2018 20:27:53 EDT WARN] [PerWorldInventory] [ECON] Unable to withdraw currency from 'twingary': Cannot withdraw negative funds
[Sat, 5. May 2018 20:27:53 EDT WARN] [PerWorldInventory] [ECON] Unable to withdraw currency from bank of 'twingary': Cannot withdraw negative funds
```

The same issue appears when I go to my creative world and come back to my survival world, my balance goes from $2,000,000 (I gave myself money to test the issue) to -$0 which doesn't make sense.

**Comment by Twingary** [comment]
Thanks for the help, I think I've found a fix to the issue.

**Comment by Gnat008** [comment]
What would that be?

**Comment by Twingary** [comment]
I couldn't really find a fix with the perworldinventory, but instead disabled the economy loading feature and replaced that with MutliWorldMoney which works fine for me. Although I still use pwi for keeping inventories and such private.

**Comment by x0Z3ro0x** [comment]
This is REALLY annoying error that doesn't seem to be getting and love. Unfortunately I am not going to follow Twingary and keep both plugins. I will just find and alternative to PWI and use that. Best of luck on fixed your issue. Just wanted to let you know this is STILL happening for the latest spigot version to date: 5/18/2018

**Comment by Gnat008** [comment]
It just occurs to me this issue is on the 1.x series. Is it still present on the 2.0 version (see [this](https://github.com/Gnat008/perworldinventory-kt/releases) page)?

**Comment by x0Z3ro0x** [comment]
> It just occurred to me this issue is on the 1.x series. Is it still present on the 2.0 version (see this page)?

I have downloaded the .jar from the page you linked. So far the error has not occurred. However it came at random for me last time. Sometimes it occurred when /gm other times it wouldn't. However you have a new issue now. If I join a world, I get the following message:

[16:27:53 WARN]: [PerWorldInventory] Creating a new group on the fly for 'Hub'. Please double check your `worlds.yml` file configuration!

However nothing is added to the worlds.yml. In addition this message is sent again and again every time myself or another OP joins a world. Even if the world is already been joined before.

**Comment by Gnat008** [comment]
@x0Z3ro0x Are your worlds in groups in your `worlds.yml` file? And could you post the answer and the contents of that file to #34 ? Thank you.

**Comment by Gnat008** [comment]
I've modified how player balances are changed. Instead of just blindly withdrawing everything and then depositing the new amount, PWI will calculate the difference between the old and new values, and deposit or withdraw that difference. This should reduce or remove this issue, as well as making the process simpler (one less API call).

**Comment by x0Z3ro0x** [comment]
It's been several hours with extensive balance changes, world changes, and GM changes. Still no sign of the bug. I believe your changes have fixed this and we can mark it solved.

**Comment by Gnat008** [comment]
Awesome! Thanks!
