### ISSUE TITLE
Loading and saving player data doesn't seem to respect GameMode separation settings

### ISSUE THREAD

**Issue by Spartan9802** [Gnat008/perworldinventory-kt#40]
Hello,
I noticed in the debug mode that the inventory was not reloaded after some world change.

Console Debug:
```
1.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] Checking cache for player data for 'newambroise' with key: ProfileKey{uuid='7c889d47-2e4c-35a6-a607-9b521ae59d39', group='default', gameMode='creative'}
11.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] Player 'newambroise' not in cache, loading from disk
11.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] Saving data for player 'newambroise' in file 'plugins/PerWorldInventory/data/7c889d47-2e4c-35a6-a607-9b521ae59d39/viste_creative.json'
11.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] Writing player data for player 'newambroise' to file
11.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] [SERIALIZER] Serializing player 'newambroise'
11.05 19:37:25 [Server] INFO [PerWorldInventory] [DEBUG] [SERIALIZER] Done serializing player 'newambroise'
```

Config:
https://pastebin.com/KcPejGXn

**Comment by Gnat008** [comment]
Currently there are no messages set to print to the console for de-serializing player information; it just happens. One can be added, I just have to decide where.

You mention an error in the title, what is it?

**Comment by Gnat008** [comment]
@Spartan9802 can you clarify based on my comment above?

**Comment by Spartan9802** [comment]
Yeah, excuse me, I didn't have time to answer.
I don't get mistakes just when my players move from a default group world to a visit group world all goes well but when he returns to a visit group world, the inventory is deleted and he stays in fly

**Comment by Gnat008** [comment]
Are there any errors in the console/logs when this happens? Also can you post the contents of your `worlds.yml` file so I know what I'm looking at?

**Comment by Spartan9802** [comment]
No, i dont have error in the console ^^
My worlds.yml
https://pastebin.com/KcPejGXn

**Comment by Gnat008** [comment]
So to make sure I have this right, players go from default to visite correctly, but things are lost when they go back to the default group?

**Comment by Spartan9802** [comment]
Yeah, that's right.
Here is the additional information
```
# The gamemode set is configured in the worlds.yml file
manage-gamemodes: false
# If true, players will have different inventories for each gamemode
separate-gamemode-inventories: false
```

**Comment by Spartan9802** [comment]
Okay, I hope you can fix this problem :)

**Comment by Gnat008** [comment]
Fixed in latest release. Thanks for the report!
