### ISSUE TITLE
New inventory not loaded when manage-gamemodes is true, but the GameMode is the same

### ISSUE THREAD

**Issue by CaptainVSGames** [Gnat008/perworldinventory-kt#45]
Group Manager File: https://pastebin.com/dZ49fJwD
Multiverse Config: https://pastebin.com/bAVA9Q8H
Multiverse Worlds: https://pastebin.com/zjAmRWqq
PWI Config: https://pastebin.com/v3aTLaS5
PWI Worlds: https://pastebin.com/b4yabvt8

Plugin List:
AdminOnly
AreaShop
AsyncWorldEdit
AsyncWorldEditInjector
AuctionHouse
AutoAnnouncer
Clearlag
CoreProtect
CrateReloaded
DeathChest
EnjinMinecraftPlugin
EssentialsX
EssentialsXChat
EssentialsXGroupManager
EssentialsXSpawn
GUIBanner
Holograms
ichat
iDisguise
Jobs
LockettePro
mcMMO
Multiverse-Core
nuvotifier-universal
OpenInv
OreAnnouncer
perworldinventory
PlaceholderAPI
PlayerVaults
PluginLibrary
Questioner
RandomCoordinates
Rankup
ShopGUIPlus
SilkSpawners
SuperbVote
SuperTrails
SuperVanish
Tablist
Towny
TownyChat
TownyNameUpdater
TRInfo (Custom /clearchat and /website and /discord plugin)
Vault
Warnings
Worldedit
Worldguard

=====================================
I tried so many times, uninstalling then reinstalling, but I just can't get it to work. Is there something I'm doing wrong?

**Comment by Gnat008** [comment]
Can you set `logging-level` in the main PWI config to `'DEBUG'`, switch worlds, and post the console/log output?

**Comment by CaptainVSGames** [comment]
https://pastebin.com/SgyrbcxD

This is the debug for it.

**Comment by Gnat008** [comment]
Are there any startup errors? Both groups are being created on the fly, which shouldn't be happening since they're both in your `worlds.yml` file...

**Comment by CaptainVSGames** [comment]
There are no startup errors.

**Comment by bmlzootown** [comment]
Same issue here. Upon updating from 1.x to 2.0, inventory groups no longer remain separate, and all output is nearly identical to Captain's (sans world group names/world names).

**Comment by Gnat008** [comment]
With debugging enabled, what is the output from `/pwi reload` or a server restart?

**Comment by bmlzootown** [comment]
[Debugging Output](https://pastebin.com/gdLQh1Ye)

**Comment by tmellen** [comment]
I'm getting the exact same thing:

> 
22.06 21:01:02 [Server] WARN [PerWorldInventory] Creating a new group on the fly for 'world'. Please double check your `worlds.yml` file configuration!
22.06 21:01:02 [Server] WARN [PerWorldInventory] Creating a new group on the fly for 'Anura'. Please double check your `worlds.yml` file configuration!
22.06 21:01:02 [Server] INFO [LumineUtils] (io.lumine.utils.) is bound to plugin MythicMobs - io.lumine.xikage.mythicmobs.MythicMobs
22.06 21:01:05 [Server] INFO [Metrics] Server returned HTTP response code: 500 for URL: http://mcstats.org/report/EpicGlass
22.06 21:01:08 [Server] WARN [PerWorldInventory] Creating a new group on the fly for 'Outbreak'. Please double check your `worlds.yml` file configuration!
> 

And the worlds are in my config:

>
groups:
  default:
    worlds:
      world
      world_nether
      world_the_end
      Anura
      Io
      Outbreak
      Skaro
      TARDIS_TimeVORTEX
      Tutorial
      antiquity
      newnewyork
    default-gamemode: SURVIVAL
  creator:
    worlds:
      wbuilds
      Buildworld
    default-gamemode: CREATIVE
>

Nothing I do makes this work.

**Comment by Gnat008** [comment]
@tmellen All of your world names need a `- ` in front of them, as they're in a YAML list. Double check the examples.

As for the rest, I'm still trying to figure out why that happens on your servers and not mine....

**Comment by SoraShiunin** [comment]
Seems to happen to me as of the plugin rewrite as well. I get this error when the server starts https://hastebin.com/gocesimuza.sql

**Comment by SoraShiunin** [comment]
https://hastebin.com/gobohiweca.makefile

**Comment by Gnat008** [comment]
@SoraShiunin there is an extra space before `default-gamemode`. YAML doesn't like that.

**Comment by Gnat008** [comment]
@CaptainVSGames now how did *that* happen... How were your groups edited, by hand or in-game commands?

**Comment by CaptainVSGames** [comment]
@Gnat008 I did it by hand at first, then the same thing happened. Deleted and reinstalled the plugin, then did it in-game. Same thing.

**Comment by tmellen** [comment]
Sorry that was the last config by hand before I said "screw it".

Even when doing /PWI addgroup TheWorlds Survival world outbreak anura etc...
and /pwi addgroup Buildworlds creative buildworld wbuilds

The file generated by the plugin... as soon as I go to one of those worlds, I lose my inventory and the plugin has created a new group with that world in it.

**Comment by tmellen** [comment]
I've had this crap show up too:

    worlds: !!set
      world: null
      world_nether: null
      world_the_end: null

**Comment by tmellen** [comment]
And you'll not that there are no hyphens in front, as generated by the plugin.

**Comment by Gnat008** [comment]
I believe I have found that problem. Why that didn't happen in testing, I have no idea.

**Comment by Gnat008** [comment]
@tmellen @CaptainVSGames Can you guys quickly stop your servers, fix your worlds files, try this attached version, and tell me if there is any improvement?

Don't extract the zip, just rename it to a `.jar`.
[perworldinventory-kt-2.0.1.zip](https://github.com/Gnat008/perworldinventory-kt/files/2130305/perworldinventory-kt-2.0.1.zip)

**Comment by CaptainVSGames** [comment]
@Gnat008 The worlds file isn't breaking anymore, but the inventories are still not changing. I have the inventory set to "true". Economy is also not changing. I deopped myself then teleported myself to the world via console. The only thing that works currently is the separate inventories per gamemode. https://hastebin.com/unomasazon.pas

**Comment by Gnat008** [comment]
@CaptainVSGames What do you have `manage-gamemodes` set to in the config? I have a hunch that I found the problem, but want to hear this answer first.

**Comment by Gnat008** [comment]
@CaptainVSGames Nevermind, I got you confused with someone else. You already posted your config. Okay. Means my hunch is likely correct. Here, try this one:
[perworldinventory-kt-2.0.1.zip](https://github.com/Gnat008/perworldinventory-kt/files/2130451/perworldinventory-kt-2.0.1.zip)

**Comment by CaptainVSGames** [comment]
@Gnat008 Still nothing. The worlds file is perfectly fine. I'll post my config again just in case I missed something. The gamemode still change no problem. Economy still doesn't split, inventories, etc...

config.yml: https://hastebin.com/aqohimukaf.coffeescript
worlds.yml: https://hastebin.com/juquyepiqe.php

**Comment by Gnat008** [comment]
@CaptainVSGames debug output? I added a couple messages in that one.

**Comment by CaptainVSGames** [comment]
@Gnat008 Here it is, sorry for not doing it before. https://pastebin.com/eQHdchfh

**Comment by Gnat008** [comment]
Okay, now I fully understand all parts of the issue. This build should take care of it once and for all. If you could just verify that for me, please. :)
[perworldinventory-kt-2.0.1.zip](https://github.com/Gnat008/perworldinventory-kt/files/2131270/perworldinventory-kt-2.0.1.zip)

**Comment by CaptainVSGames** [comment]
@Gnat008 I can confirm, the inventory works flawlessly. However, the economy money still transfers over. Otherwise, everything works amazing. Thank you so much for the help, and I will continue to assist you for the economy thing if you'd like, but currently, the inventory issue is resolved. I'll put my configs, worlds, and DEBUG info again just in case you'd like to fix the economy thing. If not, thank you so much for your help!

config.yml: https://hastebin.com/valiwukuye.coffeescript
worlds.yml: https://hastebin.com/tazegocidu.php
DEBUG: https://hastebin.com/iyagosivex.vbs

**Comment by Gnat008** [comment]
@CaptainVSGames Awesome! Just to keep things organized, can you open a new issue for the economy problem? Thanks.
