### ISSUE TITLE
Source: https://www.spigotmc.org/resources/per-world-inventory.4482/ (reviews)

### ISSUE THREAD

**Issue by Sitieno14** [Gnat008/perworldinventory-kt#47]
Porkchop
Version: v2.0.1
I used the latest version thinking it would fix the issue, but nope, players are still losing inventories randomly, and i cant seem to duplicate it. I always end up having to replace someones inventory because they lost all their survival stuff and instead have their creative inventory

Porkchop
Version: v2.0.0
Plugin is very buggy, half the time, players will come back from the creative world on my server and will lose their survival stuff and have creative stuff instead, worlds not configured to sometimes still share the same inventory, too many bugs to be reliable on a large server.

I'm not related to Porkchop, just reporting it here, I didn't experience this bug cause I didn't updated yet to v2.0

**Comment by Gnat008** [comment]
Without actually having him here to get some debugging information, opening this was entirely useless. If he or anyone else wants to help figure it out, they are free to open an issue themselves.
