### ISSUE TITLE
API - new event (InventoryLoadedEvent)

### ISSUE THREAD

**Issue by Rocologo** [Gnat008/perworldinventory-kt#50]
Hi Gnatt

Im the dev of MobHunting / BagOfGold I would like to use you API for my BagOfGolf plugin.

I have found "InventoryLoadEvent" but I need an event to be called AFTER you have updated the player inventory. Would it be possible for you to make this?

Kind regards
Rocologo

**Comment by Gnat008** [comment]
@Rocologo Does the event I added provide what you need? https://github.com/Gnat008/perworldinventory-kt/blob/master/src/main/kotlin/me/ebonjaeger/perworldinventory/event/InventoryLoadCompleteEvent.kt

**Comment by Rocologo** [comment]
Yes, it is perfect. Thank you.

**Comment by Gnat008** [comment]
Resolved by https://github.com/Gnat008/perworldinventory-kt/commit/6efa66747a8bf191bb24123453d9717bd19f8f71

**Comment by Rocologo** [comment]
Where can I find the build with a working jar?
