### ISSUE TITLE
Die when changing world with 3 hearts

### ISSUE THREAD

**Issue by Oruss7** [Gnat008/perworldinventory-kt#58]
Hello,

I have 2 worlds. 
In the second world (delerorn), players have only 3 hearts.

When players changes world to second, they die...

Can you fix that please ?

Thanks

Technical informations:
Version: 2.0.1
worlds: https://pastebin.com/g7FH8Si6
config: https://pastebin.com/R2y9jC8e

**Comment by Oruss7** [comment]
Spigot not PWI. Issue closed.

**Comment by Gnat008** [comment]
Good to know! Could you elaborate for future reference?

**Comment by Oruss7** [comment]
It seems that when a player change world and in the destination world, the player does not have 20 hearts, he dies. This bug doesn' t occur every times. Maybe the changeMaxHealth() function set health to 0 and then set health to correct amount. I don't know...

**Comment by Oruss7** [comment]
I'm not sure, but I found the problem @Gnat008. If health > max_health, spigot kill the player when switching. So, i set health = desired_max_health then max_health = desired_max_health. No more death =)

**Comment by Oruss7** [comment]
The problem persist with PWI. I use an other plugin to switch the health.

**Comment by Gnat008** [comment]
If health is greater than max health, spigot throws an exception, it doesn't kill the player. You have something else going on. I'd suspect another plugin doing something incorrect. You can see how PWI handles health in the ProfileManager class.
