### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rocologo** [Gnat008/perworldinventory-kt#59]
Hi Gnat

Does PWI manage the players Bank Balance" if the Economy plugin supports Banks? 

Kind regards 
Rocologo

**Comment by Gnat008** [comment]
No because so few use the feature. And the big ones that don't really mishandle banks; it was the cause of a lot of money duplication and shenanigans.

**Comment by Rocologo** [comment]
Tell me about money duplication. I have had so many problems with my BagOfGold plugin. But I think I got it on control now :-)
