### ISSUE TITLE
Bug my survival inventory i swapping with creative forth and back...

### ISSUE THREAD

**Issue by Rocologo** [Gnat008/perworldinventory-kt#63]
Hi Gnat
Im still working on my BagOgGold plugin and I stop and start my test server very fast, and I have discovered a strange behavior.

1) I start my test server
2) I login - in survival 
3) i add some stone in my inventory (suvival)
4) I change to creative mode
5) I add dirt to the inventory (creative)
6) I change back to survival, and the inventory is loved with stone again, all fine
7) I logout with my player
8) I stop the server
9) I start the server
10) I login in survival, but now is the inventory loaded with dirt from the creative inventory???
11) I change gamemode to creative, and the inventory is loaded with stone (which should have been in survival)
12) I change back to survival
13) I logout
14) stop the server
15)start the server
16) login to survial, and not is the inventory swapped again?????

**Comment by Rocologo** [comment]
And I can replicate this behavior all the time. This is a big problem, because BagOfGold is an item-based economy - so the money swap too....

**Comment by Gnat008** [comment]
That's... Special... Does this happen with only PWI and a multi-world plugin?

**Comment by Rocologo** [comment]
I have disabled some of the test plugins to have a faster start and stop :-) but here is the complet serverlog on a start, so you can see version numbers 
https://pastebin.com/GGCDpUeW
I dont have other plugins which manipulates the complete inventory.

and my config
https://pastebin.com/Ze7hkREq

and the worlds file
https://pastebin.com/zNPD0GPc

Its my test server so I can provide you with all the logs and testing you want. Or give you access to the server, buth i will have to white list you if you need this.

**Comment by Rocologo** [comment]
I just check my config.yml again a discovered that I had

manage-gamemodes: false

This is actually not my intention - I want separate inventories for gamemodes, but it is still a bug. 

I will try to set

manage-gamemodes: true 

later today and test again

**Comment by Rocologo** [comment]
I dont know if you changed anything in V2.1.0 SNAPSHOT 96 but the problem seems not to exist anymore. I close the ticket and open it again, if I see this strange problem again.
