### ISSUE TITLE
Make sure Attributes are only used on servers where it is supported

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/perworldinventory-kt#7]
Ref https://github.com/Gnat008/PerWorldInventory/issues/285
Ref https://github.com/Gnat008/PerWorldInventory/issues/269

Don't try to use Attributes if the server doesn't have them. Some additional logic for this is already in place, but can't be tested until more functionality is in place.

**Comment by lucasvilla97** [comment]
What do you mean by Attributes? Is that an option? a Plugin? Part of the Vainilla server? Part of the spigot? I just want to know how to fix it and make the plugin works :( thanks for your time

**Comment by lucasvilla97** [comment]
Somebode else added the plugin that added Attributes. Thanks.

**Comment by Gnat008** [comment]
It's a Bukkit thing. Never knew there was a plugin for it...

**Comment by Gnat008** [comment]
Closing this now as the pre-release versions have been used by a couple people on older servers and have not complained about this problem. If it crops up again, will reopen this.
