### ISSUE TITLE
Update cache keys when the worlds file is reloaded

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/perworldinventory-kt#9]
Ref https://github.com/Gnat008/PerWorldInventory/issues/288

- - -

When the configuration is reloaded, check the cached player keys to see if any need updating. This can cause errors if a player happened to be cached for a world before it was added to a group, and the plugin was reloaded.

Steps to fix:
- On reload, iterate through all cached keys
- For each key, check if the key contains a group. 
- If not, check if a group exists with the name in the key
- If a group with the world name is found, change the key to use the group name

**Comment by itaquito** [comment]
i just stopped the server and then reopened it and it solved the problem...
Thanks! I love your fast response.... Best dev ever

**Comment by Gnat008** [comment]
You accidently put that in the wrong project. xD I'll copy your response and close out the other one for ya.

**Comment by ljacqu** [comment]
Wouldn't you be able to just clear the cache on a reload?

**Comment by Gnat008** [comment]
I suppose technically it's more of a buffer than a cache; if it get's cleared, those inventories won't be saved to the disk.

**Comment by Gnat008** [comment]
Now that data is saved to the disk when it's first created, I don't think this is much of an issue anymore.
